version: '3'
services:
  web:
    build: .
    volumes:
      - '.:/app'
    entrypoint:
      - flask
      - run
      - -h
      - 0.0.0.0
      - -p
      - '5000'
    ports:
      - '5000:5000'
    environment: &environment
      DOCKER_HOST: tcp://docker:2375
    depends_on:
      - docker
  cleaner:
    build: .
    volumes:
      - '.:/app'
    entrypoint:
      - python
      - cleaner.py
    environment: *environment
    depends_on:
      - docker
  docker:
    image: docker:dind
    privileged: true
    entrypoint:
      - dockerd
      - -H tcp://0.0.0.0:2375
